# Generated by Django 4.2 on 2025-06-14 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_stock_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='store.item'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('store', 'item'), name='unique_store_item'),
        ),
    ]
